### ISSUE TITLE
connection_made method didn't invoked

### ISSUE THREAD

**Issue by nmg1986** [quantmind/pulsar#148]
the `connection_made` method of class `ProtocolConsumer` didn't invoked when the connection is made. such as - telnet localhost 8060

**Comment by lsbardel** [comment]
Where is the code and the test case to reproduce your issue!?

**Comment by nmg1986** [comment]
the code from the echo server examples:
https://github.com/quantmind/pulsar/blob/master/examples/echo/manage.py

and i add the `connection_made` method for class `EchoProtocol` as follows:

>>>>
class EchoProtocol(pulsar.ProtocolConsumer):
    '''An echo :class:`~.ProtocolConsumer` for client and servers.

    The only difference between client and server is the implementation
    of the :meth:`response` method.
    '''
    separator = b'\r\n\r\n'
    '''A separator for messages.'''
    buffer = b''
    '''The buffer for long messages'''

    def connection_made(self, connection):
        self.logger.info('connected')
>>>>

when i run the server and telnet from another terminal, when connected, the `connection_made` method do noting!

**Comment by lsbardel** [comment]
The ``connection_made`` in the ``ProtocolConsumer`` is fired when the ``Connection`` (the protocol) creates a new consumer, i.e. when it needs to build the consumer to consume data received from the connection transport.

Therefore, simply connecting won't fire and ``connection_made`` event on the ``ProtocolConsumer`` but it will fire a ``connection_made`` event on the Connection.

Try sending a message and you should see the event fired.

To have ``connection_made`` event on the Connection, you need to add handler to it rather than the ``ProtocolConsumer``.

**Comment by nmg1986** [comment]
you mean `class EchoProtocol(pulsar.async.events.EventHandler):` ?

**Comment by nmg1986** [comment]
when i use `class EchoProtocol(asyncio.Protocol):` , it still does not work:(, can you give some examples for this ?

**Comment by lsbardel** [comment]
There was a small bug which I've fixed.
I've updated the example, it should display the message on `connection_made` event

**Comment by nmg1986** [comment]
Yes, the updated example works well, but how can i do `connection_made` and `connection_lost` in `ProtocolConsumer` not outside?
