### ISSUE TITLE
Better docs.

### ISSUE THREAD

**Issue by mdomans** [quantmind/pulsar#157]
Here's the problem. There's a bunch of concurrency frameworks. Why **pulsar** is better or at which tasks it is better?

Such high level brief actually proves two things:

* author doesn't **just** write code - he actually solves problems and problems are specific
* author understands the differences between his work and work of others in his field and is able to express that understanding as a comprehensible body of text

**Comment by Mtpc** [comment]
:+1: 

I'd particularly love a comparison with [Twisted](https://twistedmatrix.com) and [Tornado](http://www.tornadoweb.org), both using the Reactor pattern

**Comment by lsbardel** [comment]
Better docs is not a valid issue, not in this project anyway.

A valid issue covers a specific area that a person can work on.
Writing better documentation is very important but it requires a joint effort of several people, especially people that are new and have not been involved in writing pulsar like myself.
Pulsar is opened source, if you need better docs, please [feel free to help](http://quantmind.github.io/pulsar/overview.html#contributing).

I have written pulsar because I needed to and I use it everyday to earn my living.
I didn't write it to prove anything.
