### ISSUE TITLE
Document how to work with aiogevent

### ISSUE THREAD

**Issue by thedrow** [quantmind/pulsar#177]
It's not clear how pulsar can collaborate with gevent.
Simply hooking the event loop and monkey patching might work and might not.
We need to test how it works with pulsar and if the green middleware is required and document it.

**Comment by lsbardel** [comment]
Pulsar will never support gevent in its code base.
Monkey patching the standard library is not in the philosophy of pulsar.
That should not stop you doing that if it fits your needs.

On the other hand, If you want to use pulsar in an implicit asynchronous mode you can use [pulsar.apps.greenio](http://quantmind.github.io/pulsar/apps/greenio.html) module.
The greenio module can be used to create implicit HttpClients for example or, as [pulsar-odm](https://github.com/quantmind/pulsar-odm) illustrates, implicit asynchronous sqlalchemy dialect for PostgreSql.

A better place for discussing pulsar usage is the mailing list rather than the issue tracker.
