### ISSUE TITLE
Exception message in tests

### ISSUE THREAD

**Issue by steveholden** [quantmind/pulsar#193]
In `tests/async/events.py` we see at line 24 the line

    h.bind_event('finish', lambda f, exc=None: 'OK'+4)

This raises exceptions, which result in the unintelligible output `"Exception ignored in:"` in the middle of the test output stream. If it's intended to raise that exception, could the message be suppressed, or at least identify the exception?

**Comment by steveholden** [comment]
Apologies: the exceptions concerned don't appear to be related to the line in question, as they occur even when `'OK'+4` os changed to `'OK'`.

**Comment by steveholden** [comment]
I also see two messages that read "`Not Found: /bsjdhcbjsdh"` in the testing output.

**Comment by steveholden** [comment]
Additionally, please note that the "Exception ignored" message only occurs on Mac OS (Yosemite), while the "Not found" message occurs on both Mac OS and Ubuntu

**Comment by lsbardel** [comment]
Some of these messages are caused by third party libraries which pulsar uses as [soft-dependencies](https://github.com/quantmind/pulsar/blob/master/requirements-dev.txt) during unit testing.
Therefore suppressing them may be outside the power of pulsar. Having said that, the ``Exception ignored..`` message is an asyncio message not to worry about until they have finalised the library in py 3.6, i.e. no longer provisional.
