### ISSUE TITLE
wsgi error _response 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by benbve** [quantmind/pulsar#201]
[pulsartest.zip](https://github.com/quantmind/pulsar/files/135387/pulsartest.zip)

Ok enclosed is a small test project (wsgi flask). (some values will need to be changed in the common.config.config for you to get it to work)

Issue is I have been developing for some time and using pulsar 1.0.3.  Yesterday I hit a wall where I found I could not POST a file larger than about 250KB.  If I did I received the above error even when I attempted to send in chunks (error always in wsgi/server.py in _response)
Attempted debug stepping though the pulsar code and saw that all the data was received in the chunked method but it appeared to consider it received nothing.

I decided to upgrade pulsar to 1.1.2 (latest). Here I found I could not operated at all.  A simple "GET" results in the same error (in 1.1.2 - wsgi/server.py, line 399 in _response).

Considering everything else worked before what is the issue here?  Need help as this had completely blocked progress and project is already behind.

**Comment by lsbardel** [comment]
Sorry to hear your project is behind, however that has nothing to do with the development of pulsar.
If you require consultancy services check [quantmind](http://quantmind.com/contact).

In addition, you would get more help if you can provide an [mvce](http://stackoverflow.com/help/mcve) rather than a zip file.
In any case, it looks like your app is not returning a WSGI iterable in the response function, infact it is returning nothing, hence the error message.
