### ISSUE TITLE
Is there a simple interface to Actors

### ISSUE THREAD

**Issue by jkbbwr** [quantmind/pulsar#245]
Other actor frameworks make it simple to implement an actor. Either doing an event driven style, or (preferred) a call based style

```
class Greeter(pykka.ThreadingActor):
    def __init__(self, greeting='Hi there!'):
        super(Greeter, self).__init__()
        self.greeting = greeting

    def on_receive(self, message):
        print(self.greeting)
```

Does pulsar have any *simple* equivalent to this. I realistically want to subclass Actor, implement a `run` method and call `receive`

**Comment by lsbardel** [comment]
Hi, pulsar actors don't need to be overwritten.
Depending on what you want to do, there are several way of doing message passing between actors.
Check out the [examples/snippets](https://github.com/quantmind/pulsar/blob/master/examples/snippets) directory.
Maybe the ``actor1.py`` snippet can give you an idea?

I'm closing this ticket, because it is not a feature request nor a bug.
The best channels for asking these type of questions are [the mailing](https://groups.google.com/forum/?fromgroups#!forum/python-pulsar) list and stack overflow  [python-pulsar tag](http://stackoverflow.com/questions/tagged/python-pulsar).
