### ISSUE TITLE
how to send message from actor to another actor?

### ISSUE THREAD

**Issue by PeerXu** [quantmind/pulsar#276]
* **pulsar version**: 1.6.4.final
* **python version**: 3.6.1 
* **platform**: macOS 10.12.5

## Description

Hi, 

I am looking a actor framework to implement `teller-receiver` model, and pulsar seem look fit for it.

There is two application with `Foo`(`Teller`) and `Bar`(`Receiver`).

I try to bind `on_received` event to `Bar.worker`, but seem `pulsar.send` will send to `monitor` not `worker`.

thanks.

```
#! /usr/bin/env python3

import pulsar


@pulsar.command(ack=False)
async def _tell(request, data):
    await request.actor.app.receive_data(request.actor, data)


class teller:
    async def tell(self, actor, data):
        await pulsar.send(actor, '_tell', data)


class receiver:
    async def receive_data(self, recv, data):
        recv.fire_event('on_received', data=data)


class Foo(pulsar.Application, teller):

    cfg = pulsar.Config(name='foo', workers=1)

    def worker_start(self, foo, exc=None):
        foo._loop.call_soon(self.run_loop, foo)

    def run_loop(self, foo):
        self.send_message(foo)
        foo._loop.call_later(1, self.run_loop, foo)

    def send_message(self, foo):
        pulsar.ensure_future(self._send_message(foo), loop=foo._loop)

    async def _send_message(self, foo):
        pulsar.ensure_future(self.tell('bar_foobar', 'hello, world!'), loop=foo._loop)


class Bar(pulsar.Application, receiver):

    cfg = pulsar.Config(name='bar', workers=1)

    def worker_start(self, bar, exc=None):
        bar.bind_event('on_received', self.on_received)

    def on_received(self, bar, data):
        print(data)


class Foobar(pulsar.MultiApp):
    def build(self):
        yield self.new_app(Foo)
        yield self.new_app(Bar)


def main():
    Foobar().start()


if __name__ == '__main__':
    main()
```

## Expected behaviour

`Bar.on_received` function should be execute. 

`pulsar.send` should send to `Bar.worker` not `Bar.monitor`.

## Actual behaviour

`pulsar.send` send message to `Bar.monitor`

## Steps to reproduce

run [main.py](https://gist.github.com/PeerXu/2608f9498da640a191b615972303ec3f)

**Comment by lsbardel** [comment]
Hi,
This is the correct behaviour.
A monitor controls a set of workers (actors) and``bar_foobar`` is the name of the monitor of the ``Bar`` application. If you send a message to ``bar_foobar`` the monitor receives the message.

What the monitor does with the message is up to you. It can send it to one of its workers for example, a random one (workers of a monitor should be interchangeable), or you could pass the worker id in the message so that the monitor pass the message to the worker you are interested in.
But why would you want to do this? What about if that worker died? In any case you need the worker id to do such a thing. So you need a method to get the workers ids first.

This is an interesting topic of conversation but it is better served by the mailing list.
I'm closing the issue but you are more than welcome to post in the list.
https://groups.google.com/forum/?fromgroups#!forum/python-pulsar
